environment:
  rubygems_auth_token:
    secure: 93TaZT1qqtabbet6M7JxYk+d23X18xCmecYHo+qeHgVPlYPnk4PQBzNTiNpmqrrm
  nodejs_version: 8
  rust_channel: stable
  matrix:
    - platform: x64
      rust_target: x86_64-pc-windows-msvc
      ruby_version: 22-x64
    - platform: x86
      rust_target: i686-pc-windows-msvc
      ruby_version: 22

os: Visual Studio 2015

install:
  - curl -LfsS -o "%HOMEDRIVE%%HOMEPATH%\helix-runtime-0-6-3.i386.lib" "https://github.com/hone/libcruby-sys/releases/download/lib/helix-runtime-0-6-3.i386.lib"
  - curl -LfsS -o "%HOMEDRIVE%%HOMEPATH%\helix-runtime-0-6-3.x86_64.lib" "https://github.com/hone/libcruby-sys/releases/download/lib/helix-runtime-0-6-3.x86_64.lib"
  - set HELIX_LIB_DIR=%HOMEDRIVE%%HOMEPATH%
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %rust_channel% --default-host %rust_target%
  - rm rustup-init.exe
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;%PATH%
  - bundle install --path vendor/bundle
  - ruby -e "puts RbConfig::CONFIG[\'bindir\']"
  - bundle exec rake helix:copy_dll

build: false

before_test:
  - rustc -vV
  - cargo -vV
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

after_test:
  - gem build text_transform.gemspec

artifacts:
  - name: binary
    path: text_transform-*.gem
